apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lando-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lando
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: External
      external:
        metric:
          name: http_requests_per_pod
        target:
          type: AverageValue
          averageValue: "10"
