"""IAI neural network prototype.

This module provides a lightweight implementation of the architecture described in
`CONCEPT_IAI.md`: ILL -> IPS -> CLL with an energy-aware escalation path.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, List, Sequence, Tuple


@dataclass(frozen=True)
class TelemetryInput:
    """Raw system state consumed by the Intuitive Learning Layer (ILL)."""

    battery_level: float
    cpu_demand: float
    cpu_temp_c: float
    network_mbps: float
    disk_iops: float
    latency_ms: float


@dataclass(frozen=True)
class ContradictionTensor:
    """Compact dichotomous tensor generated by ILL."""

    features: Tuple[float, ...]


@dataclass
class DecagonalTopology:
    """10-column topology with a central routing node between columns 5 and 6."""

    default_columns: List[int] = field(
        default_factory=lambda: [1, 2, 3, 5, 5, 5, 5, 5, 5, 1]
    )
    central_node_index: int = 5

    def shape_for_complexity(self, complexity: float) -> List[int]:
        """Expand columns 4-8 proportionally to complexity then cap to preserve stability."""
        shape = self.default_columns.copy()
        expansion = min(max(int(complexity * 2), 0), 4)
        for idx in range(3, 8):
            shape[idx] = min(9, shape[idx] + expansion)
        return shape


class IntuitiveLearningLayer:
    """Encodes raw telemetry into contradiction-aware tensors."""

    @staticmethod
    def _clamp_ratio(value: float) -> float:
        return min(1.0, max(0.0, value))

    def encode(self, telemetry: TelemetryInput) -> ContradictionTensor:
        battery = self._clamp_ratio(telemetry.battery_level)
        cpu_demand = self._clamp_ratio(telemetry.cpu_demand)

        # Low-battery + high-demand is an internal contradiction that should
        # increase as battery drops below the safety midpoint.
        internal_contradiction = cpu_demand * max(0.0, 0.5 - battery)
        external_contradiction = max(0.0, telemetry.network_mbps - 100) * max(
            0.0, telemetry.disk_iops - 3000
        )
        synthesis_contradiction = telemetry.latency_ms * (telemetry.cpu_temp_c / 100.0)

        opposing_aspects = (
            cpu_demand - battery,
            telemetry.network_mbps / 1000.0 - telemetry.disk_iops / 10000.0,
            telemetry.cpu_temp_c / 100.0 - telemetry.latency_ms / 500.0,
        )

        return ContradictionTensor(
            features=(
                internal_contradiction,
                external_contradiction,
                synthesis_contradiction,
                *opposing_aspects,
            )
        )


@dataclass
class InstinctCircuit:
    name: str
    signature: Tuple[float, ...]
    action: str


class InstinctiveProblemSolvingLayer:
    """Sparse reflexive circuits for fast, low-energy decisions."""

    def __init__(self, circuits: Sequence[InstinctCircuit]):
        self.circuits: List[InstinctCircuit] = list(circuits)

    @staticmethod
    def _distance(a: Sequence[float], b: Sequence[float]) -> float:
        return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5

    def resolve(self, tensor: ContradictionTensor) -> Tuple[str, float]:
        if not self.circuits:
            return "no_reflex", 0.0

        ranked = sorted(
            (
                (
                    circuit,
                    self._distance(tensor.features, circuit.signature),
                )
                for circuit in self.circuits
            ),
            key=lambda item: item[1],
        )
        best, dist = ranked[0]
        confidence = 1.0 / (1.0 + dist)
        return best.action, confidence

    def add_circuit(self, circuit: InstinctCircuit) -> None:
        self.circuits.append(circuit)


class CognitionLearningLayer:
    """Higher-order reasoner that synthesizes new instincts when worthwhile."""

    def __init__(self, planner: Callable[[ContradictionTensor], str] | None = None):
        self._planner = planner or self._default_planner

    @staticmethod
    def _default_planner(tensor: ContradictionTensor) -> str:
        internal, external, synthesis, *_ = tensor.features
        if synthesis > 2.0:
            return "reduce_request_queue_and_rebalance_threads"
        if external > 300:
            return "shape_network_traffic_and_batch_disk_writes"
        if internal > 0.15:
            return "apply_cpu_throttle_and_enable_power_saver"
        return "maintain_policy_with_predictive_monitoring"

    def deliberate(self, tensor: ContradictionTensor, energy_budget: float) -> Tuple[str, float]:
        action = self._planner(tensor)
        # Budget-aware confidence: more available energy allows deeper reasoning loops.
        cognitive_confidence = min(0.98, 0.6 + 0.3 * energy_budget)
        return action, cognitive_confidence


@dataclass
class IAIResult:
    action: str
    confidence: float
    source_layer: str
    topology: List[int]


class IAIDecisionEngine:
    """End-to-end IAI engine with escalation and instinct synthesis."""

    def __init__(self, threshold: float = 0.55):
        self.threshold = threshold
        self.topology = DecagonalTopology()
        self.ill = IntuitiveLearningLayer()
        self.ips = InstinctiveProblemSolvingLayer(
            circuits=[
                InstinctCircuit(
                    name="battery_cpu_conflict",
                    signature=(0.2, 0.0, 0.5, 0.5, 0.0, 0.2),
                    action="apply_cpu_throttle_and_enable_power_saver",
                ),
                InstinctCircuit(
                    name="io_contention",
                    signature=(0.0, 500.0, 1.0, 0.0, 0.8, 0.0),
                    action="shape_network_traffic_and_batch_disk_writes",
                ),
            ]
        )
        self.cll = CognitionLearningLayer()

    def decide(self, telemetry: TelemetryInput, energy_budget: float = 0.5) -> IAIResult:
        tensor = self.ill.encode(telemetry)
        reflex_action, reflex_conf = self.ips.resolve(tensor)

        complexity = min(1.0, sum(abs(x) for x in tensor.features) / 30.0)
        topology = self.topology.shape_for_complexity(complexity)

        if reflex_conf >= self.threshold:
            return IAIResult(reflex_action, reflex_conf, "IPS", topology)

        action, confidence = self.cll.deliberate(tensor, energy_budget)

        expected_gain = confidence - reflex_conf
        if expected_gain > 0.2:
            self.ips.add_circuit(
                InstinctCircuit(
                    name=f"learned_{len(self.ips.circuits)}",
                    signature=tensor.features,
                    action=action,
                )
            )

        return IAIResult(action, confidence, "CLL", topology)
